### PR TITLE
WIP: Add entry points compatible with Next.js App Router

### PR DESCRIPTION
**Pull request by JohnAlbin**
This pull request is for: (mark with an "x")
- [ ] `examples/*`
- [ ] `modules/next`
- [x] `packages/next-drupal`
- [ ] `starters/basic-starter`
- [ ] `starters/graphql-starter`
- [ ] Other

GitHub Issue: #442

## Describe your changes

Adds six new entry points so that developers can be more selective of which parts of the code base they import into their Server Components.

### CODE REVIEW

**Comment by JohnAlbin** [comment]
The `microbundle` build is failing in the CI with:

```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

The build is about 5.5x slower in the CI than my local laptop. Which means the failing build would take about 2.4 minutes to complete if it wasn't running out of memory. :-p Previous builds took 21 seconds in the CI.

**Comment by pookmish** [comment]
I'm getting an error when using the new experimental release:

```
⨯ node_modules/next-drupal/dist/index.modern.js (1063:22) @ eval
 ⨯ TypeError: jsona__WEBPACK_IMPORTED_MODULE_0__ is not a constructor
    at eval (webpack-internal:///(rsc)/./node_modules/next-drupal/dist/index.modern.js:1063:23)
```

I encountered this when using any functions, for example `getMenu`. I've double checked and `jsona` is installed.

**Comment by amarincolas** [comment]
> I'm getting an error when using the new experimental release:
> 
> ```
> ⨯ node_modules/next-drupal/dist/index.modern.js (1063:22) @ eval
>  ⨯ TypeError: jsona__WEBPACK_IMPORTED_MODULE_0__ is not a constructor
>     at eval (webpack-internal:///(rsc)/./node_modules/next-drupal/dist/index.modern.js:1063:23)
> ```
> 
> I encountered this when using any functions, for example `getMenu`. I've double checked and `jsona` is installed.

Same here

**Comment by JohnAlbin** [comment]
Thanks for testing this PR release out. It was _supposed_ to be a drop-in replacement for 1.6.0, but it's not working correctly. This is why we test! :D

I'm not able to reproduce the jsona-related error. Instead I get a different error:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'node_modules/next/router'
 imported from node_modules/next-drupal/dist/index.modern.js
```

I know what is causing this error, so I'll fix that. I'm opening up a new PR with a different approach.

**Comment by JohnAlbin** [comment]
BTW, with [the new PR release](https://github.com/chapter-three/next-drupal/pull/583), I _am_ getting a `TypeError: Jsona is not a constructor` error now.

**Pull request closed without merging**
