### PR TITLE
Redirects docs: added example and note about pathPrefix

### PR DESCRIPTION
**Pull request by theRuslan**

### CODE REVIEW

**Comment by TheRuslan** [comment]
Sorry for the mess. There should be only last commit #181 [12c412e](https://github.com/chapter-three/next-drupal/pull/181/commits/12c412e309c744cc0b9dc4d800c8b7f0292cc887)

**Comment by TheRuslan** [comment]
The reason is that Drupal will search through redirects for path with prefix of original locale, but nextjs sending path without locale prefix for default locale so no redirects are matching.

**Comment by shadcn** [comment]
@TheRuslan Is this still an issue with the DrupalClient?

**Comment by TheRuslan** [comment]
@shadcn yes, this is relevant for DrupalClient too.

**Comment by TheRuslan** [comment]
Merged this with the new file structure (with Guides)

**Comment by roundpanda** [comment]
This fixed my issue with setting up redirect for my multilingual site. Maybe this should get merged?

**Review by JohnAlbin — APPROVED** [review]

**Pull request merged**
