### PR TITLE
fix(next-drupal): check for versionable resource type 

### LINKED ISSUE #371: Preview error when Navigating from Versionable Entity to Non-Versionable Entity
This is a follow up of #351.

Steps to reproduce:

- Open a Entity in Preview Mode, which supports revisions 
- While in Preview Mode navigate to an Entity which doesn't support revisions
- Fails to load with error message:
```
Error: 501 Not Implemented
Resource versioning is not yet supported for this resource type.
```
The URL parameters from the json API call, when navigating from node to product page:
`fields%5Bproduct--voucher%5D=title%2Cstatus%2Cfield_description%2Cfield_image%2Cdefault_variation%2Cvariations%2Cpath%2Cfield_metatag_title%2Cfield_metatag_description%2Cfield_indexiert&include=%0A%20%20%20%20%20%20%20%20%20%20field_image%2C%0A%20%20%20%20%20%20%20%20%20%20field_image.field_media_image%0A%20%20%20%20%20%20%20%20%20%20&resourceVersion=rel%3Alatest-version`

The resourceVersion gets added to the API call, which leads to the error.

The Error only occurs, when you **preview a revisonable Entity and then navigate to a non-revisionable Entity** while in Preview Mode. 
**Directly Previewing a non-revisionable Entity works fine.** (opening it from the Drupal backend)

I guess `resourceVersion` parameter gets somehow saved and passed on in the following requests.

### PR DESCRIPTION
**Pull request by shadcn**
Fixes #371

### CODE REVIEW

**Comment by shadcn** [comment]
@yogglio Thanks. I'll look into the failing tests and tag a new release.

**Comment by shadcn** [comment]
@yogglio I made a few changes. Would you be able to test again? Thank you.

**Review by yogglio — APPROVED** [review]
@shadcn 
I tested it again and it still works.

**Review by yogglio — APPROVED** [review]

**Comment by yogglio** [comment]
Thank you very much!

**Pull request merged**
