### PR TITLE
Allow 1.x and 2.x of "cweagans/composer-patches".

### PR DESCRIPTION
**Pull request by rajeshreeputra**
This pull request is for: (mark with an "x")
- [ ] `modules/next`

GitHub Issue: #704 
_Please add a link to the GitHub issue
where this problem is discussed._

- [ ] I need help adding tests. (mark with an "x")
      _Code changes need test coverage. If you don't know
      how to make tests, check this box to ask for help._

## Describe your changes
Allow "cweagans/composer-patches" both versions i.e. 1.x and 2.x.

### CODE REVIEW

**Review by JohnAlbin — CHANGES_REQUESTED** [review]
The installation instructions for Next Drupal already include requiring composer-patches to the Drupal project using the Next module. From https://next-drupal.org/learn/quick-start/apply-patches

That means this require line in the module's composer.json is redundant/can conflict with with the Drupal project's composer.json.

I think the proper fix to support either 1.x or 2.x of composer-patches is to remove the `"cweagans/composer-patches": "~1.0",` line from `modules/next/composer.json`

**Comment by rajeshreeputra** [comment]
Yes, we can update `"cweagans/composer-patches": "~2.0"`.

**Comment by JohnAlbin** [comment]
> Yes, we can update "cweagans/composer-patches": "~2.0".

That's not what I requested. Removing the `composer-patches` requirement from the Next module will allow support for all versions of `composer-patches` from any project that requires Next module.

**Review by JohnAlbin — CHANGES_REQUESTED** [review]
> Yes, we can update "cweagans/composer-patches": "~2.0".

That's not what I requested. Removing the `composer-patches` requirement from the Next module will allow support for all versions of `composer-patches` from any project that requires Next module.

**Comment by rajeshreeputra** [comment]
That make more sense to me and that will be great, thank you.

**Review by JohnAlbin — APPROVED** [review]
Perfect!

**Comment by rajeshreeputra** [comment]
Considering your availability, can we anticipate the release on Drupal.org in a couple of weeks. Thank you!

**Comment by rajeshreeputra** [comment]
@JohnAlbin can get this released on Drupal.org, thank you!

**Comment by vishalkhode1** [comment]
> @JohnAlbin can get this released on Drupal.org, thank you!

+1

**Comment by JohnAlbin** [comment]
@rajeshreeputra @vishalkhode1 It's been on Drupal.org since March 12. https://www.drupal.org/project/next/releases/2.x-dev

Also, a new alpha or beta release will be made in the next couple weeks.

**Pull request merged**
