### PR TITLE
Use destruction events at a later runtime

### LINKED ISSUE #444: Kernel::TERMINATE over drupal_register_shutdown_function
`drupal_register_shutdown_function`calls to `register_shutdown_function` which will run after the HTTP kernel has been terminated and could cause interaction with a partially disassembled service container.

There is a paradigm for this in the terminate process of the request. This is documented here: https://symfony.com/doc/current/components/http_kernel.html#8-the-kernel-terminate-event

### PR DESCRIPTION
**Pull request by mglaman**
This pull request is for: (mark with an "x")

- [ ] `examples/*`
- [x] `modules/next`
- [ ] `packages/next-drupal`
- [ ] `starters/basic-starter`
- [ ] `starters/graphql-starter`
- [ ] Other

GitHub Issue: fixes #444

- [ ] I need help adding tests. (mark with an "x")
      _Code changes need test coverage. If you don't know
      how to make tests, check this box to ask for help._

## Describe your changes

See issue – converts from inappropriate `drupal_register_shutdown_functioncalls` to destruction service so that the container is available, appropriately.

### CODE REVIEW

**Comment by mglaman** [comment]
Looks blocked on https://github.com/chapter-three/next-drupal/pull/605

**Comment by JohnAlbin** [comment]
@mglaman #605 has been merged.

It looks like the PHP tests are failing on coding standards issue.  You can run `yarn phpcs` to test PHP coding standards on your local git clone.

**Comment by mglaman** [comment]
Thanks! I'll tidy that up after holiday break

**Comment by JohnAlbin** [comment]
There's still some phpcs errors.

```
FILE: ...modules/next/src/EventSubscriber/EntityActionEventDispatcher.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 15 | ERROR | Missing short description in doc comment
    |       | (Drupal.Commenting.DocComment.MissingShort)
 20 | ERROR | Parameter $eventDispatcher is not described in
    |       | comment
    |       | (Drupal.Commenting.FunctionComment.ParamMissingDefinition)
 23 | ERROR | Doc comment for parameter $next_entity_type_manager
    |       | does not match actual variable name
    |       | $eventDispatcher
    |       | (Drupal.Commenting.FunctionComment.ParamNameNoMatch)
----------------------------------------------------------------------
```

From #444:
> This is preventing the ability to write tests. I notice that https://github.com/chapter-three/next-drupal/blob/main/modules/next/tests/src/Kernel/Event/EntityActionEventTest.php is explicitly invoking _drupal_shutdown_function but tests which do not fail

What changes should make to our tests related to this comment?

**Comment by mglaman** [comment]
I think phpcs and tests can be fixed. I can rebase this onto one commit with proper commit messaging

**Review by Ateee89 — APPROVED** [review]

**Review by JohnAlbin — CHANGES_REQUESTED** [review]
This is looking good.

There's just one test failure now.
```
There was 1 failure:

1) Drupal\Tests\next\Kernel\Plugin\PathRevalidatorTest::testRevalidate
Some predictions failed:
Double\ClientInterface\P1:
  No calls have been made that match:
      Double\ClientInterface\P1->request(exact("GET"), exact("http://blog.com/api/revalidate?slug=/node/2"))
    but expected at least one.
  No calls have been made that match:
      Double\ClientInterface\P1->request(exact("GET"), exact("http://marketing.com/api/revalidate?slug=/node/3&secret=12345"))
    but expected at least one.
  No calls have been made that match:
      Double\ClientInterface\P1->request(exact("GET"), exact("http://blog.com/api/revalidate?slug=/node/3"))
    but expected at least one.
  No calls have been made that match:
      Double\ClientInterface\P1->request(exact("GET"), exact("http://marketing.com/api/revalidate?slug=/&secret=12345"))
    but expected at least one.
  No calls have been made that match:
      Double\ClientInterface\P1->request(exact("GET"), exact("http://marketing.com/api/revalidate?slug=/blog&secret=12345"))
    but expected at least one.
  No calls have been made that match:
      Double\ClientInterface\P1->request(exact("GET"), exact("http://blog.com/api/revalidate?slug=/"))
    but expected at least one.
  No calls have been made that match:
      Double\ClientInterface\P1->request(exact("GET"), exact("http://blog.com/api/revalidate?slug=/blog"))
    but expected at least one.
```

**Review by JohnAlbin — APPROVED** [review]
All the tests pass!

**Pull request merged**
